config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :markers
  resources :subcategories
  resources :categories
  root 'markers#index'
  get 'api', to: 'categories#api'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :subcategory
  has_many :types
  def to_s
    name
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]

  # GET /markers or /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    @subcategories = Subcategory.all
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)
    @markers = Marker.all
    respond_to do |format|
      if @marker.save
        format.js { render nothing: true, notice: "Marker was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: "Marker was successfully updated." }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:name, :url, :subcategory_id)
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_data.html.erb
<% @markers.each do |marker| %>
      <tr>
        <td><%= marker.name %></td>
        <td><%= marker.url %></td>
        <td><%= marker.subcategory %></td>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

app/views/markers/_form.html.erb
<%= form_with(model: marker, local: false) do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :subcategory_id %>
    <%= form.collection_select :subcategory_id, @subcategories, :id, :name %> 
  </div>

  <div class="actions">
    <%= form.submit 'Create Mark', data: { confirm: 'Are your sure?' } %>
  </div>
<% end %>

app/views/markers/create.js.erb
$("#data").html("<%=escape_javascript render('markers/data', marker:@marker)%>")
$("#renderForm").html(" ")

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Markers</h1>
<div id='renderForm'></div>
  <table class='table bg-secundary'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Url</th>
        <th>Subcategory</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody id='data'> 
      <%= render('markers/data') %> 
  </tbody>
</table>

<br>

<%= link_to 'New Marker', new_marker_path, remote: true, class:"btn btn-secondary text-light" %>

app/views/markers/index.js.erb
$("#data").html("<%=escape_javascript(render partial: 'markers/data', @markers => @markers)%>")

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/new.js.erb
$('#renderForm').html("<%=escape_javascript render('markers/form', marker:@marker)%>")

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @marker.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @marker.url %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @marker.subcategory %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>